"""rename card_message to message

Revision ID: 9cf21b0be190
Revises: eaa63a691f5c
Create Date: 2026-01-07 02:02:18.646556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf21b0be190'
down_revision = 'eaa63a691f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('card_message', new_column_name='message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('message', new_column_name='card_message')

    # ### end Alembic commands ###
