"""backfill owner and set not null

Revision ID: eaa63a691f5c
Revises: efbf77c0c4b1
Create Date: 2026-01-06 00:19:19.518941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa63a691f5c'
down_revision = 'efbf77c0c4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill existing NULL owner values before setting NOT NULL constraint
    op.execute("UPDATE boards SET owner='Unknown' WHERE owner IS NULL")
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
