"""add owner to boards

Revision ID: efbf77c0c4b1
Revises: f41ae36f4838
Create Date: 2026-01-06 00:09:59.304807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbf77c0c4b1'
down_revision = 'f41ae36f4838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to avoid NOT NULL constraint failures on existing rows
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
